fn main() {
    // Declares `list_decisions` to the ACL so a permission for it is
    // autogenerated (`allow-list-decisions` / `deny-list-decisions`) and can
    // be granted in a capability file. Without this, the webview cannot call
    // the command at all, regardless of what `capabilities/default.json`
    // lists — Tauri v2 gates app-defined commands the same as plugin ones.
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(&["list_decisions"]));

    tauri_build::try_build(attributes).expect("failed to run tauri-build");
}
